version: '3'

services:
  app:
    image: kevinduy/react-native
    restart: always
    environment:
      - NODE_ENV=development
    volumes:
      - ./:/app
    ports:
      - "19000:19000"
      - "19001:19001"
      - "8081:8081"
      - "3000:3000"
    links:
      - mongodb
    tty: true

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - .docker/db:/data/db
